v1.8.3
Changelog:
- Android 12 support
- Additional boot complete check
- Multi-User support
- Set ignore for GMS and IMS WRITE_SETTINGS
- Minor improvements

Signed-off-by: Gloeyisk <gloeyisk@gmail.com>

diff --git a/gmsc b/gmsc
--- a/gmsc
+++ b/gmsc
@@ -3,21 +3,21 @@
 #
 # Universal GMS Doze by the
 # open source loving 'GL-DP' and all contributors;
-# GMS Checker v1.1
+# GMS Checker v1.2
 #
 
 # Root check
 id=`id`; id=`echo ${id#*=}`; id=`echo ${id%%\(*}`; id=`echo ${id%% *}`
- if [ "$id" != "0" ] && [ "$id" != "root" ]; then
- echo "Required superuser rights!"
- exit 1
+if [ "$id" != "0" ] && [ "$id" != "root" ]; then
+ echo "Superuser (su) rights is required!"
+  exit 1
  else
 # Command-line for check whether Google Play services is optimized or not
 # Run 'gmsc' within superuser rights
 gms=`dumpsys deviceidle whitelist | grep -o com.google.android.gms | head -n 1`	
  if [ "$gms" = "com.google.android.gms" ]; then
- echo "\033[0;31m Google Play services is Not Optimized \033[0m"
- else
- echo "\033[0;32m Google Play services is Optimized \033[0m"
+  echo "\033[0;31m Google Play services is Not Optimized \033[0m"
+   else
+  echo "\033[0;32m Google Play services is Optimized \033[0m"
  fi
- fi
+fi
